"""refactored running_log with overholt model

Revision ID: 20abb0274ba6
Revises: None
Create Date: 2014-04-21 22:12:41.846375

"""

# revision identifiers, used by Alembic.
revision = '20abb0274ba6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rundetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=510), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('groups_users')
    op.drop_table('groups')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), server_default="nextval('groups_id_seq'::regclass)", nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'groups_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('groups_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], [u'groups.id'], name=u'groups_users_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'groups_users_user_id_fkey')
    )
    op.drop_table('rundetails')
    ### end Alembic commands ###
